import React from 'react';
import licenserOld from '../assets/data/licensers.json';
import _ from 'lodash';
import { finalRemapNitagCountry } from '../assets/data/nitag-countries';

/**
 * Header Component
 *
 * @component
 * @namespace Header
 * @returns {JSX.Element} The Header component that displays the main title and a welcome message.
 *
 * @example
 * // Example usage of Header component
 * <Header />
 */

const Header = () => {

    const nitagNew = [
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei Darussalam",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Democratic Republic of Congo, Kinshasa",
        "Congo, Brazzaville",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Timor-Leste",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Ivory Coast",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "North Korea",
        "South Korea",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "North Macedonia",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestine",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Russia",
        "Rwanda",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe"
    ];

    // const nitagOld = finalRemapNitagCountry.map((x) => x[0]);

    const unreachableCountry = [
        "Kuwait",
        "Cambodia",
        "Georgia",
        "Chad",
        "Congo, Brazzaville",
        "Dominica",
        "Timor-Leste",
        "Ecuador",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Kiribati",
        "Liberia",
        "Libya",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Nauru",
        "Sao Tome and Principe",
        "Somalia",
        "South Sudan",
        "Tonga",
        "Tuvalu",
        "Uganda (Very Slow)",
        "Yemen",
        "Zambia",
        "Algeria",
        "Morocco",
        "Cape Verde"
    ]

    // console.log(_.difference(nitagOld, nitagNew));
    // console.log(_.difference(licenserOld.map((x) => x !== undefined && x.country), unreachableCountry));
    const nonEnglishCountry = [
        null,
        null,
        null,
        "United Kingdom",
        "Canada",
        "Australia",
        "Germany",
        "China",
        "India",
        "Japan",
        "Mexico",
        "Singapore",
        "South Africa",
        "Brazil",
        "Russia",
        "Switzerland",
        "Hungary",
        "France",
        "Italy",
        "Spain",
        "South Korea",
        "Czech Republic",
        "Denmark",
        "Finland",
        "Greece",
        "Iceland",
        "Ireland",
        "Slovakia",
        "Slovenia",
        "Sweden",
        "Netherlands",
        "Norway",
        "Malta",
        "Romania",
        "Croatia",
        "Cyprus",
        "Estonia",
        "Portugal",
        "Colombia",
        "Nigeria",
        "Egypt",
        "Argentina",
        "Chile",
        "Israel",
        "Turkey",
        "Saudi Arabia",
        "United Arab Emirates",
        "Qatar",
        "Bahrain",
        "Oman",
        "Jordan",
        "Lebanon",
        "Iraq",
        "Syria",
        "Afghanistan",
        "Pakistan",
        "Bangladesh",
        "Sri Lanka",
        "Nepal",
        "Bhutan",
        "Maldives",
        "Indonesia",
        "Malaysia",
        "Thailand",
        "Vietnam",
        "Laos",
        "Myanmar",
        "Philippines",
        "Brunei",
        "Mongolia",
        "Kazakhstan",
        "Uzbekistan",
        "Turkmenistan",
        "Kyrgyzstan",
        "Tajikistan",
        "Armenia",
        "Azerbaijan",
        "Belarus",
        "Ukraine",
        "Moldova",
        "Serbia",
        "Montenegro",
        "Bosnia and Herzegovina",
        "North Macedonia",
        "Albania",
        "Bulgaria",
        "Angola",
        "Antigua and Barbuda",
        "Bahamas",
        "Barbados",
        "Belize",
        "Bolivia",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cameroon",
        "Central African Republic",
        "Comoros",
        "Democratic Republic of Congo, Kinshasa",
        "Djibouti",
        "Dominican Republic",
        "Eswatini",
        "Ethiopia",
        "Fiji",
        "Gabon",
        "Gambia",
        "Ghana",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Iran",
        "Ivory Coast",
        "Jamaica",
        "Kenya",
        "Lesotho",
        "Liechtenstein",
        "Luxembourg",
        "Madagascar",
        "Malawi",
        "Marshall Islands",
        "Micronesia",
        "Monaco",
        "Mozambique",
        "Namibia",
        "Nicaragua",
        "Niger",
        "Palau",
        "Palestine",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Rwanda",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Solomon Islands",
        "Suriname",
        "Tanzania",
        "Togo",
        "Trinidad and Tobago",
        "Tunisia",
        "Uganda",
        "Vanuatu",
        "Zimbabwe",
        "United States",
        "Andorra",
        "Austria",
        "Belgium",
        "Costa Rica",
        "Cuba",
        "Latvia",
        "Lithuania",
        "New Zealand",
        "Poland",
        "Sudan",
        "Uruguay",
        "Venezuela",
        "North Korea",
        "Taiwan",
        "Benin",
        "Vatican City"
    ];

    const nonEnglish = [
        "Colombia",
        "Egypt",
        "Chile",
        "Türkiye (has toggle EN but not all content are written in English)",
        "Iraq",
        "Syria",
        "Nepal (has toggle EN but not all content are written in English)",
        "Albania",
        "Angola (had to toggle for English)",
        "Bolivia",
        "Burkina Faso",
        "Burundi",
        "Comoros",
        "Central African Republic",
        "Democratic Republic of Congo, Kinshasa",
        "Djibouti",
        "Dominican Republic",
        "Gabon",
        "Guatemala",
        "Guinea",
        "Haiti",
        "Honduras",
        "Ivory Coast",
        "Madagascar",
        "Mozambique",
        "Niger",
        "Palestine",
        "Panama",
        "Paraguay",
        "Peru",
        "San Marino",
        "Senegal",
        "Suriname (had to toggle for English)",
        "Togo",
        "Andorra",
        "Costa Rica",
        "Cuba",
        "Poland",
        "Uruguay",
        "Venezuela",
        "Benin"
    ]

    // console.log(_.difference(nonEnglishCountry, nonEnglish))
    return <div className='row bg-primary text-white pt-3 pb-2 slide-down'>
        <div className='col-12 w-100' style={{ cursor: 'pointer' }} onClick={() => window.location.href = "/"}>
            <h3 className='subheading mb-0' style={{ color: '#D17728' }}></h3>
            <div className='d-inline-flex justify-content-between align-items-center w-100'>
                <img className='heading' src="/images/vacci-profile-logo.png" alt="vacciprofile logo" width={210} height={100} />
                <span style={{ color: '#D17728' }}>VacciProfile Last updated: 21, August 2025 16:49 (GMT+8)</span>
            </div>
        </div>
    </div>
};

export default Header;